openapi: 3.0.1
info:
  title: monster-hydra
  x-cortex-tag: monster-hydra
  x-cortex-custom-metadata:
    alignment: chaotic-good
    type: construct
    challenge_rating: 3
    legendary: false
    armor_class: 19
    hit_points: 107
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-hydra
      alias: github-token-test
